apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-backend
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 1
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: raaz199/map_backend:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: map-backend-srv
spec:
  type: LoadBalancer
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 32000