apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-frontend
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 1
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: raaz199/map_frontend:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: map-frontend-srv
spec:
  type: LoadBalancer
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000